name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          
      - name: Run tests
        run: go test -v ./...
        
      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o binlog-find-time-linux-amd64 ./cmd/
          GOOS=darwin GOARCH=amd64 go build -o binlog-find-time-darwin-amd64 ./cmd/
          GOOS=windows GOARCH=amd64 go build -o binlog-find-time-windows-amd64.exe ./cmd/
          
      - name: Create Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          gh release create "$TAG_NAME" \
            --title "Release $TAG_NAME" \
            --generate-notes \
            ./binlog-find-time-linux-amd64 \
            ./binlog-find-time-darwin-amd64 \
            ./binlog-find-time-windows-amd64.exe